"""Lowering of the typed MIR to native code.

The MIR is mapped instruction by instruction onto the textual LLVM IR
builder of ``llvm`` (the same representation the rest of the package
uses); the generated module text is then JIT-compiled with
``llvmlite.binding`` (MCJIT).

Compilation is module-at-a-time: :class:`LLVMBackend` lowers a whole group
of MIR functions into *one* LLVM module and adds it to a single,
process-wide engine, so calls between them become in-module ``define``
references.  Calls to functions compiled in earlier modules become
``declare``d symbols carrying the exporter's link name; the engine
resolves a module's imports by name from the modules it already holds
(it is kept alive, so everything it compiled stays callable).  The
unique link names live in the host's symbol table (``fn.SymbolTable``),
not in this backend.

The Python-facing entry of a native function is the value-form function
itself, except when the machine ABI cannot carry its arguments or result
through ctypes: an aggregate (struct or array) formal is passed as a
pointer there, and an aggregate result is written through a trailing out
pointer (the thunk then returns void).  The entry is the MIR thunk
generated by ``fn._make_thunk``, which loads the aggregate arguments and
calls the value-form function.  Spy-to-spy calls never go through the
thunk: they call the value-form function directly.
"""

import ctypes
from typing import Any

from llvmlite import binding as llvm

from . import llvm as sllvm
from . import mir
from .errors import CompileError
from .fn import Backend, NativeFn
from .util import StrBiMap, sanitize_name

llvm.initialize_native_target()
llvm.initialize_native_asmprinter()

_ICMP_OPS = {
    '==': sllvm.IcmpOp.EQ,
    '!=': sllvm.IcmpOp.NE,
    '<': sllvm.IcmpOp.LT,
    '<=': sllvm.IcmpOp.LE,
    '>': sllvm.IcmpOp.GT,
    '>=': sllvm.IcmpOp.GE,
}

_CTYPE_INT = {
    (8, True): ctypes.c_int8,
    (8, False): ctypes.c_uint8,
    (16, True): ctypes.c_int16,
    (16, False): ctypes.c_uint16,
    (32, True): ctypes.c_int32,
    (32, False): ctypes.c_uint32,
    (64, True): ctypes.c_int64,
    (64, False): ctypes.c_uint64,
}


class _ModuleTypes:
    """The LLVM types of one module: the struct types are created once
    per module (their identity is what LLVM type compatibility checks
    use), mirroring the MIR struct types of the functions being
    lowered."""

    def __init__(self) -> None:
        self._structs: dict[mir.StructType, sllvm.StructType] = {}

    def to_llvm(self, type: mir.MayBeVoidType) -> sllvm.Type:
        match type:
            case mir.VoidType():
                return sllvm.VoidType()
            case mir.BoolType():
                return sllvm.IntType(1)
            case mir.IntType():
                return sllvm.IntType(type.bits)
            case mir.FloatType():
                return sllvm.FloatType(type.bits)
            case mir.PointerType():
                return sllvm.PointerType(self.to_llvm(type.elem))
            case mir.ArrayType():
                return sllvm.ArrayType(self.to_llvm(type.elem), type.length)
            case mir.FunctionType():
                return sllvm.fn_type(
                    self.to_llvm(type.return_type),
                    *(self.to_llvm(a) for a in type.args),
                )
            case mir.StructType():
                ret = self._structs.get(type)
                if ret is None:
                    ret = sllvm.StructType(
                        sanitize_name(type.name_base or 'anon'),
                        *(self.to_llvm(f.type) for f in type.fields),
                    )
                    self._structs[type] = ret
                return ret
            case _:
                raise CompileError(f'type {type!r} cannot be lowered to LLVM')

    def struct_types(self) -> list[sllvm.Type]:
        return list(self._structs.values())


def _ctypes_of_int(bits: int, signed: bool) -> Any:
    for width in (8, 16, 32, 64):
        if bits <= width:
            return _CTYPE_INT[(width, signed)]
    return ctypes.c_int64 if signed else ctypes.c_uint64


def to_ctype(type: mir.MayBeVoidType) -> Any:
    """The ctypes type of a MIR type crossing the native boundary
    (``None`` for a void result)."""
    match type:
        case mir.VoidType():
            return None
        case mir.BoolType():
            return ctypes.c_bool
        case mir.IntType():
            return _ctypes_of_int(type.bits, type.signed)
        case mir.FloatType():
            return ctypes.c_float if type.bits == 32 else ctypes.c_double
        case mir.PointerType():
            return ctypes.c_void_p
        case mir.StructType():
            return struct_ctype(type)
        case mir.ArrayType():
            # an array crosses the boundary as its elements in a row
            ctype = to_ctype(type.elem)
            assert ctype is not None, 'an array element has a ctypes type'
            return ctype * type.length
        case _:
            raise CompileError(f'type {type!r} has no ctypes mapping')


def struct_ctype(struct: mir.StructType) -> type[ctypes.Structure]:
    """The ctypes ``Structure`` subclass mirroring the memory layout of
    the MIR struct ``struct`` - the ctypes type of a struct value in the
    generated native prototype.  The class is built once and cached on
    the MIR type."""
    cls = struct.ctype
    if cls is None:
        fields: list[tuple[str, Any]] = []
        for i, field in enumerate(struct.fields):
            ctype = to_ctype(field.type)
            assert ctype is not None
            fields.append((field.name or f'field{i}', ctype))
        cls = type(
            sanitize_name(struct.name_base or 'anon'),
            (ctypes.Structure,),
            {'_fields_': fields, '__module__': __name__},
        )
        struct.ctype = cls
    return cls


def py_entry_arg_ctype(type: mir.Type) -> Any:
    """The ctypes type of one *argument of the Python-facing entry*: an
    aggregate formal passed by reference (struct or array) is a pointer
    there (the entry is the MIR thunk generated by ``fn._make_thunk``,
    which loads the aggregate and calls the value-form function)."""
    if isinstance(type, (mir.StructType, mir.ArrayType)):
        return ctypes.c_void_p
    ctype = to_ctype(type)
    assert ctype is not None
    return ctype


class _Lowerer:
    """Lowers the flat instruction lists of the MIR functions of one
    module onto their shared ``sllvm.Function`` definitions (each list
    becomes a chain of LLVM basic blocks; an ``If`` branches into its
    two marker-delimited regions, whose falling branches join the code
    after the matching ``End``).  A call whose callee is a
    :class:`mir.Function` - of the module itself, or a function that is
    being compiled into it (recursion) - references the in-module
    ``define``; a call to a :class:`mir.ExternAnonSymbol` of an earlier
    module references a (cached) extern declaration."""

    def __init__(
        self,
        globals: StrBiMap[mir.GlobalValue],
        types: _ModuleTypes,
    ) -> None:
        self._types = types
        self._lowered: dict[object, sllvm.Value] = {}
        self._globals = globals
        self.lowered_globals: dict[mir.GlobalValue, sllvm.GlobalValue] = {}

    def _to_llvm(self, type: mir.MayBeVoidType) -> sllvm.Type:
        return self._types.to_llvm(type)

    def _lower_function_no_cache(self, fn: mir.Function) -> sllvm.Function:
        """Lower the basic blocks of ``fn`` into its pre-created
        ``sllvm.Function``: every MIR block becomes one LLVM block and its
        terminator becomes the ``ret``/``jmp``/``br`` ending it.

        Every ``mir.Alloca`` is lowered into the function's entry block
        first, whatever block the interpreter emitted it in: a slot may
        first be stored inside a runtime branch, and its address must then
        be defined on every path that stores to it or reads it later."""
        assert fn not in self.lowered_globals
        llvm_fn = sllvm.Function(self._globals.get_key(fn))
        # register the definition before lowering the body: a call to this
        # function inside its own body (recursion) must resolve to it
        self.lowered_globals[fn] = llvm_fn
        llvm_fn.add_args(*(self._to_llvm(a) for a in fn.args))
        llvm_fn.set_return_type(self._to_llvm(fn.ret_type))

        arg_values = llvm_fn.get_args()
        blocks = fn.entry.collect_blocks()
        # the MIR entry block *is* the LLVM entry block, so that the
        # hoisted slots have a unique home; every other block is fresh
        block_map: dict[int, sllvm.BasicBlock] = {
            id(block): (llvm_fn.entry if block is fn.entry else sllvm.BasicBlock())
            for block in blocks
        }
        for block in blocks:
            for inst in block.insts:
                if isinstance(inst, mir.Alloca):
                    self._lower_inst(llvm_fn.entry, inst, arg_values, block_map)
        for block in blocks:
            target = block_map[id(block)]
            for inst in block.insts:
                if isinstance(inst, mir.Alloca):
                    # already lowered into the entry block
                    continue
                self._lower_inst(target, inst, arg_values, block_map)
        return llvm_fn

    def _value(self, value: mir.Value, arg_values: tuple[sllvm.Value, ...]) -> sllvm.Value:
        if isinstance(value, mir.Param):
            return arg_values[value.index]
        if isinstance(value, mir.Inst):
            ret = self._lowered.get(id(value))
            if ret is None:
                raise CompileError('internal error: instruction not lowered yet')
            return ret
        if isinstance(value, mir.BoolValue):
            return sllvm.IntValue(1 if value.value else 0, sllvm.IntType(1))
        if isinstance(value, mir.Int):
            return sllvm.IntValue(value.value, sllvm.IntType(value.type.bits))
        if isinstance(value, mir.Float):
            return sllvm.FloatType(value.type.bits).from_float(value.value)
        if isinstance(value, mir.NullValue):
            ptr_type = self._to_llvm(value.type)
            assert isinstance(ptr_type, sllvm.PointerType)
            return sllvm.NullValue(ptr_type)
        if isinstance(value, mir.GlobalValue):
            return self.lower_global(value)
        raise CompileError(f'cannot lower value {value!r}')

    def _lower_global_no_cache(self, value: mir.GlobalValue):
        assert value not in self.lowered_globals
        match value:
            case mir.Function():
                return self._lower_function_no_cache(value)
            case mir.ExternAnonSymbol() | mir.ExternSymbol():
                name = self._globals.get_key(value)
                if isinstance(value.type, mir.PointerType) and isinstance(value.type.elem, mir.FunctionType):
                    fn_type = self._to_llvm(value.type.elem)
                    assert isinstance(fn_type, sllvm.FnType)
                    return sllvm.DeclareFunction(name, fn_type)
                else:
                    raise NotImplementedError(f"TODO: lower global {value!r}")
            case _:
                raise NotImplementedError(f"TODO: lower global {value!r}")

    def lower_global(self, value: mir.GlobalValue) -> sllvm.GlobalValue:
        """The lowered form of a function value: the in-module
        ``define`` of a :class:`mir.Function`, or a (cached) extern
        declaration of a symbol compiled in an earlier module."""
        if value not in self.lowered_globals:
            ret = self._lower_global_no_cache(value)
            self.lowered_globals[value] = ret
        return self.lowered_globals[value]

    def _lower_inst(
        self,
        block: sllvm.BasicBlock,
        inst: mir.Inst,
        arg_values: tuple[sllvm.Value, ...],
        block_map: dict[int, sllvm.BasicBlock],
    ) -> None:
        result: sllvm.Value | None = None
        match inst:
            case mir.Alloca():
                result = block.alloca(self._to_llvm(inst.type))
            case mir.Store():
                block.store(
                    self._value(inst.ptr, arg_values), self._value(inst.value, arg_values)
                )
            case mir.Load():
                result = block.load(self._value(inst.ptr, arg_values))
            case mir.Gep():
                ptr = self._value(inst.ptr, arg_values)
                index = inst.index
                if isinstance(index, int):
                    result = block.get_element_ptr(ptr, 0, index)
                else:
                    result = block.get_element_ptr(ptr, 0, self._value(index, arg_values))
            case mir.Arith():
                lhs = self._value(inst.lhs, arg_values)
                rhs = self._value(inst.rhs, arg_values)
                match inst.op:
                    case '+':
                        result = block.add(lhs, rhs)
                    case '-':
                        result = block.sub(lhs, rhs)
                    case '*':
                        result = block.mul(lhs, rhs)
                    case '/':
                        result = block.div(lhs, rhs, inst.signed)
                    case '%':
                        result = block.rem(lhs, rhs, inst.signed)
                    case _:
                        raise CompileError(f"unsupported MIR operation '{inst.op}'")
            case mir.Convert():
                value = self._value(inst.value, arg_values)
                to = self._to_llvm(inst.type)
                match inst.kind:
                    case 'sitofp':
                        result = block.int_to_float(value, to)  # type: ignore[arg-type]
                    case 'uitofp':
                        result = block.uint_to_float(value, to)  # type: ignore[arg-type]
                    case 'fpext':
                        result = block.float_ext(value, to)  # type: ignore[arg-type]
                    case 'fptrunc':
                        result = block.float_trunc(value, to)  # type: ignore[arg-type]
                    case 'sext':
                        result = block.sext(value, to)  # type: ignore[arg-type]
                    case 'zext':
                        result = block.zext(value, to)  # type: ignore[arg-type]
                    case 'trunc':
                        result = block.emit(sllvm.IntTrunc(value, to))  # type: ignore[arg-type]
                    case 'fptosi':
                        result = block.emit(sllvm.FloatToInt(value, to))  # type: ignore[arg-type]
                    case 'fptoui':
                        result = block.emit(sllvm.FloatToUInt(value, to))  # type: ignore[arg-type]
                    case _:
                        raise CompileError(f"unsupported conversion '{inst.kind}'")
            case mir.Cmp():
                lhs = self._value(inst.lhs, arg_values)
                rhs = self._value(inst.rhs, arg_values)
                op = _ICMP_OPS[inst.op]
                if inst.kind == 'int':
                    result = block.icmp(op, inst.signed, lhs, rhs)
                else:
                    result = block.fcmp(op, lhs, rhs)
            case mir.Call():
                callee = self._value(inst.callee, arg_values)
                result = block.call(
                    callee, *(self._value(a, arg_values) for a in inst.args)
                )
            case mir.Jmp():
                block.jmp(block_map[id(inst.target)])
            case mir.Br():
                block.br(
                    self._value(inst.cond, arg_values),
                    block_map[id(inst.if_true)],
                    block_map[id(inst.if_false)],
                )
            case mir.Ret():
                block.ret(
                    None if inst.value is None else self._value(inst.value, arg_values)
                )
            case _:
                raise CompileError(f'unsupported MIR instruction {type(inst).__name__}')
        if result is not None:
            self._lowered[id(inst)] = result


class _NativeFn(NativeFn):
    """The concrete compiled artifact of one specialization: the ctypes
    entry bound to its Python-facing ABI, and the address of the lowered
    function it was built for."""

    def __init__(
        self,
        name: str,
        lines: list[str],
        addr: int,
        entry: ctypes._CFunctionType,
    ) -> None:
        self.name = name
        self._lines = lines
        self._addr = addr
        self._entry = entry

    @property
    def addr(self) -> int:
        return self._addr

    def call(self, *values: ctypes._CDataType) -> ctypes._CDataType | None:
        return self._entry(*values)

    def print_all(self) -> list[str]:
        return self._lines


class LLVMBackend(Backend):
    """The MCJIT backend of the spy compiler: lowers one MIR module at a
    time into one LLVM module and adds it to a single, reused engine.

    The MIR symbol table (``fn.SymbolTable``) has already given every
    global the unique link name it keeps across modules, so the engine
    resolves a module's external references by name: an import of an
    earlier-compiled function carries the exporter's name, and an
    ``ExternSymbol`` falls back to the process.  The engine is kept alive
    so the addresses of everything it has compiled stay valid."""

    def __init__(self) -> None:
        super().__init__()
        target = llvm.Target.from_default_triple()
        tm = target.create_target_machine()
        backing_mod = llvm.parse_assembly('')
        # one engine for the whole process: modules added to it resolve
        # each other's symbols by name
        self._engine = llvm.create_mcjit_compiler(backing_mod, tm)

    def compile(self, structs: set[mir.StructType], globals: StrBiMap[mir.GlobalValue]) -> dict[mir.GlobalValue, NativeFn]:
        types = _ModuleTypes()
        for struct in structs:
            types.to_llvm(struct)

        lowerer = _Lowerer(globals, types)

        fns: list[mir.Function] = sorted(
            (sym for sym in globals.values() if isinstance(sym, mir.Function)),
            key=lambda fn: globals.get_key(fn),
        )
        llvm_fns: dict[mir.Function, sllvm.Function] = {}
        for fn in fns:
            llvm_fn = lowerer.lower_global(fn)
            assert isinstance(llvm_fn, sllvm.Function)
            llvm_fns[fn] = llvm_fn

        lmod = sllvm.Module()
        lmod.add_recursively(values=[llvm_fns[fn] for fn in fns])
        lmod.add_recursively(types=types.struct_types())
        lmod.finish()
        lines = lmod.write()

        llvm_mod = llvm.parse_assembly('\n'.join(lines))
        llvm_mod.verify()
        self._engine.add_module(llvm_mod)
        self._engine.finalize_object()
        self._engine.run_static_constructors()

        rets: dict[mir.GlobalValue, NativeFn] = {}
        for fn in fns:
            # the link name the LLVM module actually emitted
            name = lmod.get_global_name(llvm_fns[fn])
            addr = self._engine.get_function_address(name)
            arg_ctypes: list[Any] = [py_entry_arg_ctype(a) for a in fn.args]
            restype = to_ctype(fn.ret_type)
            proto = ctypes.CFUNCTYPE(restype, *arg_ctypes)  # type: ignore[arg-type]
            entry = ctypes.cast(addr, proto)
            native = _NativeFn(
                name,
                lines,
                addr,
                entry,
            )
            rets[fn] = native
        return rets
