"""Lowering of the typed MIR to native code.

The MIR is mapped instruction by instruction onto the textual LLVM IR
builder of ``llvm`` (the same representation the rest of the package
uses); the generated module text is then JIT-compiled with
``llvmlite.binding`` (LLJIT, the ORC JIT).

Compilation is module-at-a-time: :class:`LLVMBackend` lowers a whole group
of MIR functions into *one* LLVM module and links it as a named JIT
library of a single, process-wide ORC JIT, so calls between them become
in-module ``define`` references.  Calls to functions compiled in earlier
modules become ``declare``d symbols carrying the exporter's link name;
every library linked so far is a prerequisite of the new one (the JIT's
link order is not transitive), so a module's imports resolve by name from
the libraries it already holds.  An ``ExternSymbol`` falls back to the
process.  The resource trackers of the linked libraries are kept alive,
so everything compiled stays callable.  The unique link names live in the
host's symbol table (``fn.SymbolTable``), not in this backend.

The Python-facing entry of a native function is the value-form function
itself, except when the machine ABI cannot carry its arguments or result
through ctypes: an aggregate (struct or array) formal is passed as a
pointer there, and an aggregate result is written through a trailing out
pointer (the thunk then returns void).  The entry is the MIR thunk
generated by ``fn._make_thunk``, which loads the aggregate arguments and
calls the value-form function.  Spy-to-spy calls never go through the
thunk: they call the value-form function directly.
"""

import ctypes
from typing import Any

from llvmlite import binding as llvm

from . import llvm as sllvm
from . import mir
from .errors import CompileError
from .fn import Backend, NativeFn
from .target import TargetInfo
from .util import StrBiMap, sanitize_name

llvm.initialize_native_target()
llvm.initialize_native_asmprinter()

_ICMP_OPS = {
    '==': sllvm.IcmpOp.EQ,
    '!=': sllvm.IcmpOp.NE,
    '<': sllvm.IcmpOp.LT,
    '<=': sllvm.IcmpOp.LE,
    '>': sllvm.IcmpOp.GT,
    '>=': sllvm.IcmpOp.GE,
}

# the LLVM operation of one ``mir.AtomicRmw``, by its ``op`` string
_ATOMIC_RMW_OPS = {
    'xchg': sllvm.Xchg,
    'add': sllvm.Add,
    'sub': sllvm.Sub,
    'and': sllvm.AndOp,
    'or': sllvm.OrOp,
    'xor': sllvm.XorOp,
}


def _ordering(ordering: mir.AtomicOrdering) -> sllvm.Ordering:
    """The LLVM ordering of a MIR atomic ordering (the two share their
    spellings)."""
    return sllvm.Ordering(ordering.value)


_CTYPE_INT = {
    (8, True): ctypes.c_int8,
    (8, False): ctypes.c_uint8,
    (16, True): ctypes.c_int16,
    (16, False): ctypes.c_uint16,
    (32, True): ctypes.c_int32,
    (32, False): ctypes.c_uint32,
    (64, True): ctypes.c_int64,
    (64, False): ctypes.c_uint64,
}


class _ModuleTypes:
    """The LLVM types of one module: the struct types are created once
    per module (their identity is what LLVM type compatibility checks
    use), mirroring the MIR struct types of the functions being
    lowered."""

    def __init__(self) -> None:
        self._structs: dict[mir.StructType, sllvm.StructType] = {}

    def to_llvm(self, type: mir.ReturnType) -> sllvm.Type:
        match type:
            case mir.VoidType():
                return sllvm.VoidType()
            case mir.NoReturn():
                # a function that never returns returns nothing: only its
                # ``noreturn`` attribute tells LLVM about it (see
                # ``_lower_function_no_cache``)
                return sllvm.VoidType()
            case mir.BoolType():
                return sllvm.IntType(1)
            case mir.IntType():
                return sllvm.IntType(type.bits)
            case mir.FloatType():
                return sllvm.FloatType(type.bits)
            case mir.PointerType():
                return sllvm.PointerType(self.to_llvm(type.elem))
            case mir.ArrayType():
                return sllvm.ArrayType(self.to_llvm(type.elem), type.length)
            case mir.FunctionType():
                return sllvm.fn_type(
                    self.to_llvm(type.return_type),
                    *(self.to_llvm(a) for a in type.args),
                    *((...,) if type.varargs else ()),
                )
            case mir.StructType():
                ret = self._structs.get(type)
                if ret is None:
                    fields = [self.to_llvm(f.type) for f in type.fields]
                    if type.fam_type is not None:
                        # the flexible member: a zero-length array of the element
                        # type (an ``i8`` array for an opaque tail), which adds
                        # no size but its element alignment to the struct
                        if isinstance(type.fam_type, mir.VoidType):
                            fields.append(sllvm.ArrayType(sllvm.IntType(8), 0))
                        else:
                            fields.append(sllvm.ArrayType(self.to_llvm(type.fam_type), 0))
                    ret = sllvm.StructType(
                        sanitize_name(type.name_base or 'anon'),
                        *fields,
                    )
                    self._structs[type] = ret
                return ret
            case mir.UnionType():
                # an untagged union is laid out as its storage (the largest
                # variant): a variant is read and written through a bitcast
                return self.to_llvm(type.payload)
            case _:
                raise CompileError(f'type {type!r} cannot be lowered to LLVM')

    def struct_types(self) -> list[sllvm.Type]:
        return list(self._structs.values())


def _ctypes_of_int(bits: int, signed: bool) -> Any:
    for width in (8, 16, 32, 64):
        if bits <= width:
            return _CTYPE_INT[(width, signed)]
    return ctypes.c_int64 if signed else ctypes.c_uint64


def to_ctype(type: mir.ReturnType) -> Any:
    """The ctypes type of a MIR type crossing the native boundary
    (``None`` for a void result, and for one that never returns)."""
    match type:
        case mir.VoidType() | mir.NoReturn():
            return None
        case mir.BoolType():
            return ctypes.c_bool
        case mir.IntType():
            return _ctypes_of_int(type.bits, type.signed)
        case mir.FloatType():
            return ctypes.c_float if type.bits == 32 else ctypes.c_double
        case mir.PointerType():
            return ctypes.c_void_p
        case mir.StructType():
            return struct_ctype(type)
        case mir.UnionType():
            return to_ctype(type.payload)
        case mir.ArrayType():
            # an array crosses the boundary as its elements in a row
            ctype = to_ctype(type.elem)
            assert ctype is not None, 'an array element has a ctypes type'
            return ctype * type.length
        case _:
            raise CompileError(f'type {type!r} has no ctypes mapping')


def struct_ctype(struct: mir.StructType) -> type[ctypes.Structure]:
    """The ctypes ``Structure`` subclass mirroring the memory layout of
    the MIR struct ``struct`` - the ctypes type of a struct value in the
    generated native prototype.  The class is built once and cached on
    the MIR type."""
    cls = struct.ctype
    if cls is None:
        if struct.fam_type is not None:
            # a struct with a flexible member has no value of its own: it cannot
            # cross the Python boundary (only a pointer to it can)
            raise CompileError(
                f'{struct} has a flexible member and cannot be passed by value'
            )
        fields: list[tuple[str, Any]] = []
        for i, field in enumerate(struct.fields):
            ctype = to_ctype(field.type)
            assert ctype is not None
            fields.append((field.name or f'field{i}', ctype))
        cls = type(
            sanitize_name(struct.name_base or 'anon'),
            (ctypes.Structure,),
            {'_fields_': fields, '__module__': __name__},
        )
        struct.ctype = cls
    return cls


def py_entry_arg_ctype(type: mir.Type) -> Any:
    """The ctypes type of one *argument of the Python-facing entry*: an
    aggregate formal passed by reference (struct or array) is a pointer
    there (the entry is the MIR thunk generated by ``fn._make_thunk``,
    which loads the aggregate and calls the value-form function)."""
    if isinstance(type, (mir.StructType, mir.ArrayType)):
        return ctypes.c_void_p
    ctype = to_ctype(type)
    assert ctype is not None
    return ctype


class _UnwindCtx:
    """The exception support of one function being lowered: the slot a landing
    pad leaves its exception pair in (so the function-wide resume block can pick
    it up) and the LLVM blocks that already got a landing pad.  It is *not* on
    the lowerer itself, because lowering one function may recurse into another
    (a call lowers its callee), so the state has to be per invocation."""

    def __init__(self, fn: sllvm.Function) -> None:
        self.fn = fn
        # the ``{ ptr, i32 }`` slot a landing pad stores the exception it caught
        # into, shared by every may-panic call's unwind edge of this function
        self.slot: sllvm.Value | None = None
        # the ids of the LLVM blocks that already hold a landing pad
        self.landing_pads: set[int] = set()


class _Lowerer:
    """Lowers the flat instruction lists of the MIR functions of one
    module onto their shared ``sllvm.Function`` definitions (each list
    becomes a chain of LLVM basic blocks; an ``If`` branches into its
    two marker-delimited regions, whose falling branches join the code
    after the matching ``End``).  A call whose callee is a
    :class:`mir.Function` - of the module itself, or a function that is
    being compiled into it (recursion) - references the in-module
    ``define``; a call to a :class:`mir.ExternAnonSymbol` of an earlier
    module references a (cached) extern declaration."""

    def __init__(
        self,
        globals: StrBiMap[mir.GlobalValue],
        types: _ModuleTypes,
        target: TargetInfo,
    ) -> None:
        self._types = types
        self._target = target
        self._layout = sllvm.DataLayout(target.pointer_size)
        self._lowered: dict[object, sllvm.Value] = {}
        # the instructions already lowered (a terminator has no lowered value,
        # so ``_lowered`` alone cannot tell whether one was lowered)
        self._lowered_ids: set[int] = set()
        self._globals = globals
        self.lowered_globals: dict[mir.GlobalValue, sllvm.GlobalValue] = {}

    def _to_llvm(self, type: mir.ReturnType) -> sllvm.Type:
        return self._types.to_llvm(type)

    def _lower_function_no_cache(self, fn: mir.Function) -> sllvm.Function:
        """Lower the basic blocks of ``fn`` into its pre-created
        ``sllvm.Function``: every MIR block becomes one LLVM block and its
        terminator becomes the ``ret``/``jmp``/``br`` ending it.

        Every ``mir.Alloca`` is lowered into the function's entry block
        first, whatever block the interpreter emitted it in: a slot may
        first be stored inside a runtime branch, and its address must then
        be defined on every path that stores to it or reads it later."""
        assert fn not in self.lowered_globals
        blocks = fn.entry.collect_blocks()
        # the exception support of this body: a may-panic call with deferred
        # bodies to run, a ``catch_unwind`` and the function-wide resume all use
        # a landing pad, so the frame needs a personality (see ``_UnwindCtx``)
        needs_personality = any(
            isinstance(inst, (mir.CallMayPanic, mir.CatchUnwind, mir.Resume))
            or (isinstance(inst, mir.Panic) and inst.unwind_path is not None)
            for block in blocks for inst in block.insts
        )
        needs_slot = any(
            isinstance(inst, (mir.CallMayPanic, mir.Resume))
            or (isinstance(inst, mir.Panic) and inst.unwind_path is not None)
            for block in blocks for inst in block.insts
        )
        llvm_fn = sllvm.Function(
            self._globals.get_key(fn),
            noreturn=isinstance(fn.ret_type, mir.NoReturn),
            personality=sllvm.GXX_PERSONALITY if needs_personality else None,
        )
        # register the definition before lowering the body: a call to this
        # function inside its own body (recursion) must resolve to it
        self.lowered_globals[fn] = llvm_fn
        llvm_fn.add_args(*(self._to_llvm(a) for a in fn.args))
        llvm_fn.set_return_type(self._to_llvm(fn.ret_type))

        arg_values = llvm_fn.get_args()
        # the MIR entry block *is* the LLVM entry block, so that the
        # hoisted slots have a unique home; every other block is fresh
        block_map: dict[int, sllvm.BasicBlock] = {
            id(block): (llvm_fn.entry if block is fn.entry else sllvm.BasicBlock())
            for block in blocks
        }
        ctx = _UnwindCtx(llvm_fn)
        if needs_slot:
            # the exception pair a landing pad hands over is kept in one slot per
            # function, so the shared resume block can pick it up; it lives in
            # the entry block like every other slot
            ctx.slot = llvm_fn.entry.alloca(sllvm.LANDING_PAD_TYPE)
        for block in blocks:
            for inst in block.insts:
                if isinstance(inst, mir.Alloca):
                    self._lower_inst(llvm_fn.entry, inst, arg_values, block_map, ctx)
        # a pointer ``BitCast`` of a stable pointer (an alloca or a parameter)
        # is resolved into the entry block first, so that it is available to
        # every block that takes the address of a union variant through it (it
        # emits no instruction of its own, see ``_lower_inst``).  A ``Gep`` of a
        # stable pointer with a constant index - the payload field of a tagged
        # union, e.g. - is hoisted the same way, so that the ``BitCast`` of it
        # can be hoisted in turn
        hoisted = True
        while hoisted:
            hoisted = False
            for block in blocks:
                for inst in block.insts:
                    if id(inst) in self._lowered_ids:
                        continue
                    if isinstance(inst, mir.BitCast):
                        operand = inst.value
                        stable = isinstance(operand, mir.Param) or (
                            isinstance(operand, mir.Inst) and id(operand) in self._lowered_ids
                        )
                    elif isinstance(inst, mir.Gep) and isinstance(inst.index, int):
                        operand = inst.ptr
                        stable = isinstance(operand, mir.Param) or (
                            isinstance(operand, mir.Inst) and id(operand) in self._lowered_ids
                        )
                    else:
                        continue
                    if stable:
                        self._lower_inst(llvm_fn.entry, inst, arg_values, block_map, ctx)
                        hoisted = True
        # lower every remaining instruction, iterating the blocks until no
        # progress: an instruction is lowered once every value it uses is, and
        # an instruction is never lowered before an earlier one of its block -
        # so the definitions stay in order and a phi, its block's first
        # instruction, is inserted at the front.  A ``Phi`` is special: a loop's
        # back-edge incoming depends on the phi itself, so it is lowered as soon
        # as one incoming is available and the rest are patched in afterwards
        # (``pending_phi_incomings``, see ``_lower_inst``)
        progress = True
        pending_phi_incomings: list[tuple[sllvm.Phi, mir.Value, mir.BasicBlock]] = []
        while progress:
            progress = False
            for block in blocks:
                for inst in block.insts:
                    if id(inst) in self._lowered_ids:
                        continue
                    if isinstance(inst, mir.Phi):
                        # a phi may be lowered as soon as one of its incomings is
                        # available (the others are added after the body, see
                        # ``_lower_inst``); a phi whose incomings are all still
                        # pending waits for a later pass
                        ready = any(
                            not (isinstance(value, mir.Inst) and id(value) not in self._lowered_ids)
                            for value, _ in inst.incomings
                        )
                        if not ready:
                            break
                        self._lower_inst(block_map[id(block)], inst, arg_values, block_map, ctx, pending_phi_incomings)
                        progress = True
                        continue
                    if not self._operands_lowered(inst):
                        break
                    self._lower_inst(block_map[id(block)], inst, arg_values, block_map, ctx)
                    progress = True
        # the back-edge incomings of the phis lowered above are available now
        for phi, value, pred in pending_phi_incomings:
            phi.add_incoming(self._value(value, arg_values), block_map[id(pred)])
        for block in blocks:
            for inst in block.insts:
                if id(inst) not in self._lowered_ids:
                    raise CompileError(f'internal error: cannot lower the MIR instruction {inst!r} in {block!r}')
        return llvm_fn

    def _operands_lowered(self, inst: mir.Inst) -> bool:
        """Whether every instruction ``inst`` uses has been lowered already."""
        for child in inst.get_children():
            if isinstance(child, mir.Inst) and id(child) not in self._lowered_ids:
                return False
        return True

    def _value(self, value: mir.Value, arg_values: tuple[sllvm.Value, ...]) -> sllvm.Value:
        if isinstance(value, mir.Param):
            return arg_values[value.index]
        if isinstance(value, mir.Inst):
            ret = self._lowered.get(id(value))
            if ret is None:
                raise CompileError('internal error: instruction not lowered yet')
            return ret
        if isinstance(value, mir.BoolValue):
            return sllvm.IntValue(1 if value.value else 0, sllvm.IntType(1))
        if isinstance(value, mir.Int):
            return sllvm.IntValue(value.value, sllvm.IntType(value.type.bits))
        if isinstance(value, mir.Float):
            return sllvm.FloatType(value.type.bits).from_float(value.value)
        if isinstance(value, mir.NullValue):
            ptr_type = self._to_llvm(value.type)
            assert isinstance(ptr_type, sllvm.PointerType)
            return sllvm.NullValue(ptr_type)
        if isinstance(value, mir.UndefValue):
            return sllvm.Undef(self._to_llvm(value.type))
        if isinstance(value, mir.Dangling):
            # a dangling pointer: the pointee's *actual* alignment as the
            # address, so it is non-null (see ``mir.Dangling``).  A pointer to a
            # zero-sized type has ``void`` as its pointee, whose alignment the
            # layout has (1).
            ptr_type = self._to_llvm(value.type)
            assert isinstance(ptr_type, sllvm.PointerType)
            align = self._layout.align_of(self._to_llvm(value.type.elem))
            return sllvm.IntToPtr(
                sllvm.IntValue(align, sllvm.IntType(self._layout.pointer_size * 8)),
                ptr_type,
            )
        if isinstance(value, mir.GlobalValue):
            return self.lower_global(value)
        raise CompileError(f'cannot lower value {value!r}')

    def _lower_global_no_cache(self, value: mir.GlobalValue):
        assert value not in self.lowered_globals
        match value:
            case mir.Function():
                return self._lower_function_no_cache(value)
            case mir.ExternAnonSymbol() | mir.ExternSymbol():
                name = self._globals.get_key(value)
                if isinstance(value.type, mir.PointerType) and isinstance(value.type.elem, mir.FunctionType):
                    fn_type = self._to_llvm(value.type.elem)
                    assert isinstance(fn_type, sllvm.FnType)
                    return sllvm.DeclareFunction(name, fn_type)
                else:
                    raise NotImplementedError(f"TODO: lower global {value!r}")
            case mir.GlobalConstant():
                return self._lower_global_constant(value)
            case mir.GlobalStringValue():
                return self._lower_global_string(value)
            case _:
                raise NotImplementedError(f"TODO: lower global {value!r}")

    def _lower_global_constant(self, constant: mir.GlobalConstant) -> sllvm.GlobalValue:
        """A global static constant: the location the pointer ``constant``
        names holds the constant value.  The initializer is a scalar or an
        aggregate; a value the module already names (a function pointer) stays
        a reference to it."""
        pointee = self._to_llvm(constant.type.elem)
        align = self._layout.align_of(pointee)
        lowered = self._lower_constant(constant.value)
        if isinstance(lowered, sllvm.AggregateConstant):
            return sllvm.GlobalAggregateValue(lowered, align=align)
        return sllvm.GlobalScalarValue(lowered, align=align)

    def _lower_global_string(self, value: mir.GlobalStringValue) -> sllvm.GlobalValue:
        """A global static constant holding a byte string: the bytes are emitted
        into a read-only global (see ``llvm.GlobalStringValue``); ``value.data``
        already carries the trailing NUL."""
        return sllvm.GlobalStringValue(value.data)

    def _lower_constant(self, constant: mir.Value | mir.AggregateConstant | mir.UnionConstant) -> sllvm.Value | sllvm.AggregateConstant:
        """Lower one constant of a global initializer: a scalar leaf to its
        LLVM value, an aggregate/union constant to a literal (see
        ``_lower_aggregate_constant`` / ``_lower_union_constant``)."""
        match constant:
            case mir.AggregateConstant():
                return self._lower_aggregate_constant(constant)
            case mir.UnionConstant():
                return self._lower_union_constant(constant)
            case _:
                return self._value(constant, ())

    def _needs_literal(self, constant: mir.AggregateConstant | mir.UnionConstant) -> bool:
        """Whether the constant must be laid out with a literal type: an
        aggregate constant can use the named types of its fields only when no
        union along it holds a variant other than its storage variant."""
        match constant:
            case mir.UnionConstant():
                return constant.variant != constant.union.payload
            case mir.AggregateConstant():
                return any(
                    self._needs_literal(member)
                    for member in constant.values
                    if isinstance(member, (mir.AggregateConstant, mir.UnionConstant))
                )
            case _:
                return False

    def _member_type(self, member: sllvm.Value | sllvm.AggregateConstant) -> sllvm.Type:
        if isinstance(member, sllvm.AggregateConstant):
            return member.type
        return member.get_type()

    def _lower_union_constant(self, constant: mir.UnionConstant) -> sllvm.Value | sllvm.AggregateConstant:
        """Lower a constant union value.  A variant that is the union's storage
        variant is stored as itself; any other one is laid out the way clang
        lays it out, as a literal ``{<variant>, [pad x i8]}`` padded to the
        storage's size (see ``mir.UnionConstant``)."""
        payload = self._to_llvm(constant.union.payload)
        if constant.variant == constant.union.payload:
            return self._lower_constant(constant.value)
        variant = self._to_llvm(constant.variant)
        pad = self._layout.size_of(payload) - self._layout.size_of(variant)
        fields = [variant]
        values: list[sllvm.Value | sllvm.AggregateConstant] = [self._lower_constant(constant.value)]
        if pad > 0:
            pad_type = sllvm.ArrayType(sllvm.I8, pad)
            fields.append(pad_type)
            values.append(sllvm.ZeroInitializer(pad_type))
        return sllvm.AggregateConstant(sllvm.LiteralStructType(*fields), *values)

    def _lower_aggregate_constant(self, constant: mir.AggregateConstant) -> sllvm.AggregateConstant:
        """Lower a constant aggregate value.  When no union member forces a
        literal type it uses the named struct/array type of the aggregate;
        otherwise it builds a literal type whose members reproduce the layout
        of that named type (explicit ``[pad x i8]`` between the fields), the way
        clang lays out a global holding a union (see ``mir.AggregateConstant``)."""
        if not self._needs_literal(constant):
            values: list[sllvm.Value | sllvm.AggregateConstant] = []
            for member in constant.values:
                values.append(self._lower_constant(member))
            mir_type = self._to_llvm(constant.type)
            assert isinstance(mir_type, sllvm.AggregateType)
            return sllvm.AggregateConstant(mir_type, *values)
        if isinstance(constant.type, mir.StructType):
            return self._lower_literal_struct(constant)
        return self._lower_literal_array(constant)

    def _lower_literal_array(self, constant: mir.AggregateConstant) -> sllvm.AggregateConstant:
        values: list[sllvm.Value | sllvm.AggregateConstant] = [
            self._lower_constant(member) for member in constant.values
        ]
        if values:
            elem = self._member_type(values[0])
        else:
            elem = self._to_llvm(constant.type.elem)  # pyright: ignore[reportAttributeAccessIssue]
        return sllvm.AggregateConstant(sllvm.ArrayType(elem, constant.type.length), *values)  # pyright: ignore[reportAttributeAccessIssue]

    def _lower_literal_struct(self, constant: mir.AggregateConstant) -> sllvm.AggregateConstant:
        assert isinstance(constant.type, mir.StructType)
        fields: list[sllvm.Type] = []
        values: list[sllvm.Value | sllvm.AggregateConstant] = []
        offset = 0
        align = 1
        for field, member in zip(constant.type.fields, constant.values):
            canonical = self._to_llvm(field.type)
            field_align = self._layout.align_of(canonical)
            pad = sllvm.align_up(offset, field_align) - offset
            if pad > 0:
                pad_type = sllvm.ArrayType(sllvm.I8, pad)
                fields.append(pad_type)
                values.append(sllvm.ZeroInitializer(pad_type))
                offset += pad
            lowered = self._lower_constant(member)
            fields.append(self._member_type(lowered))
            values.append(lowered)
            offset += self._layout.size_of(canonical)
            align = max(align, field_align)
        tail = sllvm.align_up(offset, align) - offset
        if tail > 0:
            pad_type = sllvm.ArrayType(sllvm.I8, tail)
            fields.append(pad_type)
            values.append(sllvm.ZeroInitializer(pad_type))
        return sllvm.AggregateConstant(sllvm.LiteralStructType(*fields), *values)

    def lower_global(self, value: mir.GlobalValue) -> sllvm.GlobalValue:
        """The lowered form of a function value: the in-module
        ``define`` of a :class:`mir.Function`, or a (cached) extern
        declaration of a symbol compiled in an earlier module."""
        if value not in self.lowered_globals:
            ret = self._lower_global_no_cache(value)
            self.lowered_globals[value] = ret
        return self.lowered_globals[value]

    def _lower_inst(
        self,
        block: sllvm.BasicBlock,
        inst: mir.Inst,
        arg_values: tuple[sllvm.Value, ...],
        block_map: dict[int, sllvm.BasicBlock],
        ctx: _UnwindCtx,
        pending_phi_incomings: list[tuple[sllvm.Phi, mir.Value, mir.BasicBlock]] | None = None,
    ) -> None:
        result: sllvm.Value | None = None
        match inst:
            case mir.Alloca():
                result = block.alloca(self._to_llvm(inst.type))
            case mir.Sizeof():
                result = sllvm.IntValue(
                    self._layout.size_of(self._to_llvm(inst.type)),
                    sllvm.IntType(inst.bits),
                )
            case mir.Alignof():
                result = sllvm.IntValue(
                    self._layout.align_of(self._to_llvm(inst.type)),
                    sllvm.IntType(inst.bits),
                )
            case mir.Store():
                block.store(
                    self._value(inst.ptr, arg_values), self._value(inst.value, arg_values)
                )
            case mir.Load():
                result = block.load(self._value(inst.ptr, arg_values), self._to_llvm(inst.get_type()))
            case mir.AtomicLoad():
                result = block.atomic_load(
                    self._value(inst.ptr, arg_values),
                    self._to_llvm(inst.get_type()),
                    _ordering(inst.ordering),
                    self._layout.align_of(self._to_llvm(inst.get_type())),
                    inst.volatile,
                )
            case mir.AtomicStore():
                block.atomic_store(
                    self._value(inst.ptr, arg_values),
                    self._value(inst.value, arg_values),
                    _ordering(inst.ordering),
                    self._layout.align_of(self._to_llvm(inst.value.get_type())),
                    inst.volatile,
                )
            case mir.AtomicRmw():
                result = block.atomicrmw(
                    _ATOMIC_RMW_OPS[inst.op](),
                    self._value(inst.ptr, arg_values),
                    self._value(inst.value, arg_values),
                    _ordering(inst.ordering),
                    inst.volatile,
                )
            case mir.AtomicCmpxchg():
                result = block.cmpxchg(
                    self._value(inst.ptr, arg_values),
                    self._value(inst.expected, arg_values),
                    self._value(inst.desired, arg_values),
                    _ordering(inst.success),
                    _ordering(inst.failure),
                    inst.volatile,
                )
            case mir.Fence():
                block.fence(_ordering(inst.ordering))
            case mir.Gep():
                ptr = self._value(inst.ptr, arg_values)
                index = inst.index
                index_value = index if isinstance(index, int) else self._value(index, arg_values)
                pointee_type = inst.ptr.get_type()
                pointee = (
                    self._to_llvm(pointee_type.elem)
                    if isinstance(pointee_type, mir.PointerType) else None
                )
                if isinstance(pointee, (sllvm.StructType, sllvm.ArrayType)):
                    # a field/element of the value the pointer points at: LLVM
                    # addresses it with the leading zero index
                    result = block.get_element_ptr(ptr, 0, index_value, pointee=pointee)
                else:
                    # an offset *by whole pointees* (a ``MultiPtr``, ``mptr + n``)
                    result = block.get_element_ptr(ptr, index_value, pointee=pointee)
            case mir.ExtractValue():
                result = block.extract_value(self._value(inst.value, arg_values), inst.index)
            case mir.InsertValue():
                result = block.insert_value(
                    self._value(inst.value, arg_values),
                    self._value(inst.elem, arg_values),
                    inst.index,
                )
            case mir.Select():
                result = block.select(
                    self._value(inst.cond, arg_values),
                    self._value(inst.if_true, arg_values),
                    self._value(inst.if_false, arg_values),
                )
            case mir.Arith():
                lhs = self._value(inst.lhs, arg_values)
                rhs = self._value(inst.rhs, arg_values)
                signed = isinstance(inst.type, mir.IntType) and inst.type.signed
                match inst.op:
                    case '+':
                        result = block.add(lhs, rhs)
                    case '-':
                        result = block.sub(lhs, rhs)
                    case '*':
                        result = block.mul(lhs, rhs)
                    case '/':
                        result = block.div(lhs, rhs, signed)
                    case '%':
                        result = block.rem(lhs, rhs, signed)
                    case '|':
                        result = block.or_(lhs, rhs)
                    case '&':
                        result = block.and_(lhs, rhs)
                    case '^':
                        result = block.xor(lhs, rhs)
                    case '<<':
                        result = block.shl(lhs, rhs)
                    case '>>':
                        result = block.ashr(lhs, rhs) if signed else block.lshr(lhs, rhs)
                    case _:
                        raise CompileError(f"unsupported MIR operation '{inst.op}'")
            case mir.Floor():
                result = block.floor(self._value(inst.value, arg_values))
            case mir.Pow():
                result = block.pow(
                    self._value(inst.lhs, arg_values),
                    self._value(inst.rhs, arg_values),
                )
            case mir.Convert():
                value = self._value(inst.value, arg_values)
                to = self._to_llvm(inst.type)
                match inst.kind:
                    case 'sitofp':
                        result = block.int_to_float(value, to)  # type: ignore[arg-type]
                    case 'uitofp':
                        result = block.uint_to_float(value, to)  # type: ignore[arg-type]
                    case 'fpext':
                        result = block.float_ext(value, to)  # type: ignore[arg-type]
                    case 'fptrunc':
                        result = block.float_trunc(value, to)  # type: ignore[arg-type]
                    case 'sext':
                        result = block.sext(value, to)  # type: ignore[arg-type]
                    case 'zext':
                        result = block.zext(value, to)  # type: ignore[arg-type]
                    case 'trunc':
                        result = block.emit(sllvm.IntTrunc(value, to))  # type: ignore[arg-type]
                    case 'fptosi':
                        result = block.emit(sllvm.FloatToInt(value, to))  # type: ignore[arg-type]
                    case 'fptoui':
                        result = block.emit(sllvm.FloatToUInt(value, to))  # type: ignore[arg-type]
                    case _:
                        raise CompileError(f"unsupported conversion '{inst.kind}'")
            case mir.BitCast():
                value = self._value(inst.value, arg_values)
                source_type = inst.value.get_type()
                if (
                    (isinstance(source_type, mir.PointerType) and isinstance(inst.type, mir.PointerType))
                    or self._to_llvm(source_type) == self._to_llvm(inst.type)
                ):
                    # the reinterpretation has no representation of its own when
                    # the two types lower to the same LLVM type: every pointer is
                    # the same opaque ``ptr``, and an integer's signedness (or
                    # ``bool`` against its ``i1``/``u1`` counterpart) is a
                    # compile-time notion - the LLVM type is the same, so the
                    # value is used as it is.  Its MIR type is the target, so the
                    # signedness a later instruction reads is the new one.
                    result = value
                else:
                    result = block.bitcast(value, self._to_llvm(inst.type))
            case mir.AsUnion() | mir.ExtractUnion() | mir.UnionCast():
                # a union value is laid out as its storage (the largest variant),
                # and the LLVM pointers are untyped (``ptr``): the conversion is
                # a store through the largest of the two types and a load of the
                # target one, which reinterprets the storage
                value = self._value(inst.value, arg_values)
                src = inst.value.get_type()
                assert isinstance(src, mir.Type), 'a union conversion operand has a type'
                dst = inst.type
                src_size = self._layout.size_of(self._to_llvm(src))
                dst_size = self._layout.size_of(self._to_llvm(dst))
                wide = dst if dst_size > src_size else src
                slot = block.alloca(self._to_llvm(wide))
                block.store(slot, value)
                result = block.load(slot, self._to_llvm(dst))
            case mir.Cmp():
                lhs = self._value(inst.lhs, arg_values)
                rhs = self._value(inst.rhs, arg_values)
                op = _ICMP_OPS[inst.op]
                operand_type = inst.lhs.get_type()
                if isinstance(operand_type, mir.FloatType):
                    result = block.fcmp(op, lhs, rhs)
                else:
                    # integers (a bool is an ``i1``) and pointers compare with
                    # ``icmp``; only equality is defined on pointers, so their
                    # signedness is irrelevant
                    signed = isinstance(operand_type, mir.IntType) and operand_type.signed
                    result = block.icmp(op, signed, lhs, rhs)
            case mir.Phi():
                # a phi's incomings are defined in its predecessors; a loop's
                # back-edge incoming is defined in the body and *depends on the
                # phi itself*, so a phi is created as soon as one incoming is
                # available and the rest are added once the body is lowered
                # (``pending_phi_incomings``, see ``_lower_function_no_cache``)
                available: list[tuple[mir.Value, mir.BasicBlock]] = []
                pending: list[tuple[mir.Value, mir.BasicBlock]] = []
                for value, pred in inst.incomings:
                    if isinstance(value, mir.Inst) and id(value) not in self._lowered_ids:
                        pending.append((value, pred))
                    else:
                        available.append((value, pred))
                assert available, 'a phi needs at least one available incoming'
                first_value, first_block = available[0]
                phi = sllvm.Phi((self._value(first_value, arg_values), block_map[id(first_block)]))
                for value, pred in available[1:]:
                    phi.add_incoming(self._value(value, arg_values), block_map[id(pred)])
                # an LLVM phi must lead its basic block
                block.insts.insert(0, phi)
                result = phi
                if pending_phi_incomings is not None:
                    for value, pred in pending:
                        pending_phi_incomings.append((phi, value, pred))
            case mir.Call():
                callee = self._value(inst.callee, arg_values)
                result = block.call(
                    callee, *(self._value(a, arg_values) for a in inst.args)
                )
                if inst.is_noreturn():
                    # a call of a function that never returns ends its block;
                    # LLVM wants the end of a block spelled out
                    block.unreachable()
            case mir.Jmp():
                block.jmp(block_map[id(inst.target)])
            case mir.Br():
                block.br(
                    self._value(inst.cond, arg_values),
                    block_map[id(inst.if_true)],
                    block_map[id(inst.if_false)],
                )
            case mir.Switch():
                block.switch(
                    self._value(inst.value, arg_values),
                    block_map[id(inst.default)],
                    *tuple((case, block_map[id(block0)]) for case, block0 in inst.cases),
                )
            case mir.Ret():
                block.ret(
                    None if inst.value is None else self._value(inst.value, arg_values)
                )
            case mir.Panic():
                result = self._lower_panic(block, inst, arg_values, block_map, ctx)
            case mir.CallMayPanic():
                result = self._lower_call_may_panic(block, inst, arg_values, block_map, ctx)
            case mir.CatchUnwind():
                result = self._lower_catch_unwind(block, inst, arg_values, block_map)
            case mir.Resume():
                assert ctx.slot is not None, 'a Resume needs the function unwind slot'
                exception = block.load(ctx.slot, sllvm.LANDING_PAD_TYPE)
                block.resume(exception)
            case _:
                raise CompileError(f'unsupported MIR instruction {type(inst).__name__}')
        self._lowered_ids.add(id(inst))
        if result is not None:
            self._lowered[id(inst)] = result

    def _lower_panic(
        self,
        block: sllvm.BasicBlock,
        inst: mir.Panic,
        arg_values: tuple[sllvm.Value, ...],
        block_map: dict[int, sllvm.BasicBlock],
        ctx: _UnwindCtx,
    ) -> None:
        """Throw a C++ exception carrying the ``PanicData`` ``inst.data`` points
        at (``__cxa_throw``), then ``unreachable``: the exception's ``type_info``
        is ``@_ZTIi``, the one a ``catch_unwind``'s landing pad matches.  When the
        panic would run the frame's deferred bodies, the throw is an ``invoke``
        whose unwind edge runs them first (the normal edge is unreachable)."""
        data = self._value(inst.data, arg_values)
        pointer_type = inst.data.get_type()
        assert isinstance(pointer_type, mir.PointerType)
        size = self._layout.size_of(self._to_llvm(pointer_type.elem))
        size_value = sllvm.IntValue(size, sllvm.I64)
        obj = block.call(sllvm.CXA_ALLOCATE_EXCEPTION, size_value)
        block.call(sllvm.LLVM_MEMCPY, obj, data, size_value, sllvm.BOOL_FALSE)
        throw_args = (obj, sllvm.ZTI_INT, sllvm.NullValue(sllvm.I8_PTR))
        if inst.unwind_path is not None:
            dead = sllvm.BasicBlock()
            unwind = block_map[id(inst.unwind_path)]
            self._install_unwind_landing_pad(unwind, ctx)
            block.invoke(sllvm.CXA_THROW, throw_args, dead, unwind)
            dead.unreachable()
        else:
            block.call(sllvm.CXA_THROW, *throw_args)
            block.unreachable()

    def _lower_call_may_panic(
        self,
        block: sllvm.BasicBlock,
        inst: mir.CallMayPanic,
        arg_values: tuple[sllvm.Value, ...],
        block_map: dict[int, sllvm.BasicBlock],
        ctx: _UnwindCtx,
    ) -> sllvm.Value:
        """Lower a may-panic call to an ``invoke`` whose unwind edge lands in
        the entry of the instantiated deferred-body chain (a landing pad that
        saves the exception and runs the bodies, then resumes)."""
        callee = self._value(inst.callee, arg_values)
        args = tuple(self._value(arg, arg_values) for arg in inst.args)
        normal = block_map[id(inst.normal_path)]
        unwind = block_map[id(inst.unwind_path)]
        self._install_unwind_landing_pad(unwind, ctx)
        return block.invoke(callee, args, normal, unwind)

    def _lower_catch_unwind(
        self,
        block: sllvm.BasicBlock,
        inst: mir.CatchUnwind,
        arg_values: tuple[sllvm.Value, ...],
        block_map: dict[int, sllvm.BasicBlock],
    ) -> sllvm.Value:
        """Lower a ``catch_unwind`` call to an ``invoke`` whose unwind edge lands
        in a landing pad that catches the panic and hands the thrown object (the
        ``PanicData``) to the interpreter's catch block through ``catch_data``."""
        callee = self._value(inst.callee, arg_values)
        args = tuple(self._value(arg, arg_values) for arg in inst.args)
        normal = block_map[id(inst.normal_path)]
        catch = block_map[id(inst.catch_path)]
        catch_data = self._value(inst.catch_data, arg_values)
        self._install_catch_landing_pad(catch, catch_data)
        return block.invoke(callee, args, normal, catch)

    def _first_non_phi(self, block: sllvm.BasicBlock) -> int:
        """The position a landing pad belongs at in ``block``: an LLVM landing
        pad must lead its block but every phi must still come first."""
        index = 0
        while index < len(block.insts) and isinstance(block.insts[index], sllvm.Phi):
            index += 1
        return index

    def _install_unwind_landing_pad(self, block: sllvm.BasicBlock, ctx: _UnwindCtx) -> None:
        """Give the unwind target ``block`` its cleanup landing pad: it catches
        the panic pair and stores it into the function's unwind slot, so the
        function-wide resume block can resume with it once the deferred bodies
        have run.  Created once per block (several may-panic calls can share the
        same instantiated chain)."""
        if id(block) in ctx.landing_pads:
            return
        ctx.landing_pads.add(id(block))
        assert ctx.slot is not None, 'a CallMayPanic needs the function unwind slot'
        pad = sllvm.LandingPad((), is_cleanup=True)
        at = self._first_non_phi(block)
        block.insts.insert(at, pad)
        block.insts.insert(at + 1, sllvm.Store(ctx.slot, pad))

    def _install_catch_landing_pad(self, block: sllvm.BasicBlock, catch_data: sllvm.Value) -> None:
        """Give a ``catch_unwind``'s unwind target its catching landing pad: it
        matches the panic ``type_info`` and passes the thrown object (the
        ``PanicData``) to the interpreter's catch block through ``catch_data``."""
        pad = sllvm.LandingPad((sllvm.ZTI_INT,), is_cleanup=False)
        exception = sllvm.ExtractValue(pad, (0,))
        caught = sllvm.Call(sllvm.CXA_BEGIN_CATCH, (exception,))
        at = self._first_non_phi(block)
        block.insts[at:at] = [pad, exception, caught, sllvm.Store(catch_data, caught)]


class _NativeFn(NativeFn):
    """The concrete compiled artifact of one specialization: the ctypes
    entry bound to its Python-facing ABI, and the address of the lowered
    function it was built for."""

    def __init__(
        self,
        name: str,
        lines: list[str],
        addr: int,
        entry: ctypes._CFunctionType,
    ) -> None:
        self.name = name
        self._lines = lines
        self._addr = addr
        self._entry = entry

    @property
    def addr(self) -> int:
        return self._addr

    def call(self, *values: ctypes._CDataType) -> ctypes._CDataType | None:
        return self._entry(*values)

    def print_all(self) -> list[str]:
        return self._lines


class LLVMBackend(Backend):
    """The LLJIT backend of the spy compiler: lowers one MIR module at a
    time into one LLVM module and links it as a named JIT library of a
    single, reused ORC JIT.

    The MIR symbol table (``fn.SymbolTable``) has already given every
    global the unique link name it keeps across modules, so the JIT
    resolves a module's external references by name: an import of an
    earlier-compiled function carries the exporter's name and resolves
    from the library that module was linked into (every earlier library
    is a prerequisite of the new one), and an ``ExternSymbol`` falls back
    to the process.  The resource trackers of the linked libraries are
    kept alive so the addresses of everything compiled stay valid."""

    def __init__(self) -> None:
        super().__init__()
        target = llvm.Target.from_default_triple()
        tm = target.create_target_machine()
        # one JIT for the whole process: every module becomes a named JIT
        # library, and a later library lists the earlier ones as prerequisites
        # so that cross-module references resolve by name
        self._jit = llvm.create_lljit_compiler(tm, use_jit_link=True)
        self._libraries: list[str] = []
        # the trackers keep the linked libraries (and their code) alive; the
        # backend lives as long as the process, so the addresses stay valid
        self._trackers: list[llvm.ResourceTracker] = []
        self._module_id = 0

    def compile(self, structs: set[mir.StructType], globals: StrBiMap[mir.GlobalValue], target: TargetInfo) -> dict[mir.GlobalValue, NativeFn]:
        types = _ModuleTypes()
        for struct in structs:
            types.to_llvm(struct)

        lowerer = _Lowerer(globals, types, target)

        fns: list[mir.Function] = sorted(
            (sym for sym in globals.values() if isinstance(sym, mir.Function)),
            key=lambda fn: globals.get_key(fn),
        )
        llvm_fns: dict[mir.Function, sllvm.Function] = {}
        for fn in fns:
            llvm_fn = lowerer.lower_global(fn)
            assert isinstance(llvm_fn, sllvm.Function)
            llvm_fns[fn] = llvm_fn

        lmod = sllvm.Module()
        lmod.add_recursively(values=[llvm_fns[fn] for fn in fns])
        lmod.add_recursively(types=types.struct_types())
        lmod.finish()
        lines = lmod.write()

        # parse + verify before handing the module to the JIT, so bad IR
        # reports a clear error
        text = '\n'.join(lines)
        llvm_mod = llvm.parse_assembly(text)
        llvm_mod.verify()

        # link the module as a fresh named library; it may reference any
        # earlier module, so every library linked so far is a prerequisite of
        # the new one (the JIT's link order is not transitive), while
        # unresolved externals fall back to the process
        builder = llvm.JITLibraryBuilder().add_ir(text).add_current_process()
        for lib in self._libraries:
            builder.add_jit_library(lib)
        for fn in fns:
            builder.export_symbol(lmod.get_global_name(llvm_fns[fn]))
        lib_name = f'spy_module_{self._module_id}'
        self._module_id += 1
        tracker = builder.link(self._jit, lib_name)
        self._libraries.append(lib_name)
        self._trackers.append(tracker)

        rets: dict[mir.GlobalValue, NativeFn] = {}
        for fn in fns:
            # the link name the LLVM module actually emitted
            name = lmod.get_global_name(llvm_fns[fn])
            addr = tracker[name]
            arg_ctypes: list[Any] = [py_entry_arg_ctype(a) for a in fn.args]
            restype = to_ctype(fn.ret_type)
            proto = ctypes.CFUNCTYPE(restype, *arg_ctypes)  # type: ignore[arg-type]
            entry = ctypes.cast(addr, proto)
            native = _NativeFn(
                name,
                lines,
                addr,
                entry,
            )
            rets[fn] = native
        return rets
